interface ArgusLockupProps {
  className?: string;
  /** Accessible name. The wordmark is artwork, so the name is supplied here. */
  label?: string;
}

/**
 * The wordmark is outlined to paths — Fira Sans Medium at 16% tracking — so the
 * letterforms are identical wherever the brand appears rather than resolving to
 * whatever sans-serif the reader's system supplies.
 *
 * Generated by `docs/brand/generate.py`; keep in step with
 * `docs/brand/argus-lockup.svg`.
 */
export function ArgusLockup({ className, label = 'Argus' }: ArgusLockupProps) {
  return (
    <svg
      viewBox="0 0 191.2 52"
      className={className}
      role="img"
      aria-label={label}
      focusable="false"
    >
      <g transform="translate(3 3) scale(0.71875)">
        <path
          className="fill-brand-soft"
          d="M40.289 37.000C33.589 44.109 24.093 49.744 12.000 53.000L18 45C23.776 43.075 28.662 40.408 32.031 37.000Z"
        />
        <path
          className="fill-signal"
          d="M52 8C52.000 18.698 47.994 28.824 40.289 37.000L32.031 37.000C37.410 31.557 38.920 24.224 34.000 15.000Z"
        />
        <path
          className="fill-brand"
          d="M8.5 32.0H55.5A2.5 2.5 0 0 1 58.0 34.5V39.5A2.5 2.5 0 0 1 55.5 42.0H8.5A2.5 2.5 0 0 1 6.0 39.5V34.5A2.5 2.5 0 0 1 8.5 32.0Z"
        />
      </g>
      <path
        className="fill-brand"
        transform="translate(67.0 38.0)"
        d="M15.53 0.00H20.39L12.96 -24.00H7.29L-0.17 0.00H4.58L6.08 -5.56H14.03ZM6.98 -9.03 10.04 -20.49 13.09 -9.03Z M39.72 0.00H45.00L38.71 -10.45C41.98 -11.74 43.57 -13.68 43.57 -16.95C43.57 -21.71 40.34 -24.00 34.06 -24.00H26.90V0.00H31.49V-9.62H34.40ZM31.49 -20.67H33.95C37.29 -20.67 38.78 -19.55 38.78 -16.95C38.78 -14.07 37.18 -12.92 34.33 -12.92H31.49Z M61.65 -24.52C55.65 -24.52 50.64 -20.14 50.64 -12.02C50.64 -3.79 54.39 0.52 61.24 0.52C64.26 0.52 67.11 -0.38 69.50 -1.84V-13.58H60.89L61.38 -10.18H64.99V-3.92C63.84 -3.26 62.52 -2.99 61.17 -2.99C57.42 -2.99 55.47 -5.45 55.47 -12.02C55.47 -18.48 58.39 -21.05 61.79 -21.05C63.84 -21.05 65.20 -20.42 66.83 -19.14L69.30 -21.71C67.28 -23.41 64.99 -24.52 61.65 -24.52Z M95.47 -24.00H90.85V-8.09C90.85 -4.72 89.49 -3.06 86.51 -3.06C83.55 -3.06 82.20 -4.72 82.20 -8.09V-24.00H77.62V-7.85C77.62 -2.92 80.60 0.52 86.51 0.52C92.38 0.52 95.47 -3.02 95.47 -7.85Z M111.50 -24.52C106.78 -24.52 103.34 -21.88 103.34 -17.89C103.34 -14.24 105.52 -12.23 110.56 -10.66C114.31 -9.52 115.32 -8.61 115.32 -6.60C115.32 -4.27 113.48 -3.02 110.91 -3.02C108.41 -3.02 106.50 -3.92 104.73 -5.42L102.36 -2.78C104.34 -0.83 107.19 0.52 111.01 0.52C116.74 0.52 120.11 -2.54 120.11 -6.84C120.11 -11.36 117.20 -13.09 112.99 -14.41C109.00 -15.66 108.06 -16.43 108.06 -18.16C108.06 -20.04 109.62 -21.01 111.78 -21.01C113.76 -21.01 115.42 -20.39 117.16 -18.96L119.42 -21.57C117.33 -23.48 115.01 -24.52 111.50 -24.52Z"
      />
    </svg>
  );
}
